<?php
bolt_decrypt( __FILE__ , 'bJWEjJ'); return 0;
##!!!##BgZqXWlhb2xdX2EcPWxsWExdX2ddY2FvWE1xYW51QXRwbl1YQXRfYWxwZWtqbzcGBnFvYRxBdF9hbHBla2o3BgZfaF1vbxxFanJdaGVgUF1eaGEcYXRwYWpgbxxBdF9hbHBla2oGdwYcHBwcKyYmBhwcHBwcJhxOYWxrbnAccGRhHGF0X2FscGVraioGHBwcHBwmBhwcHBwcJhw8bmFwcW5qHHJrZWAGHBwcHBwmKwYcHBwcbHFeaGVfHGJxal9wZWtqHG5hbGtucCQlBhwcHBx3BhwcHBx5Bnk=