<?php
bolt_decrypt( __FILE__ , 'qpXuAC'); return 0;
##!!!##PDygk5+XpaKTlZdSc6KijoKTlZ2TmZeljoOnl6Srd6qmpJOOd6qVl6Kmm6GgpW08PKell1J3qpWXoqaboaBtPDyVnpOlpVJ7oKiTnpuWg6eXpKtSl6qml6CWpVJ3qpWXoqaboaA8rTxSUlJSYVxcPFJSUlJSXFKEl6KhpKZSppqXUpeqlZeippuhoGA8UlJSUlJcPFJSUlJSXFJypJemp6SgUqihm5Y8UlJSUlJcYTxSUlJSoqeUnpuVUpinoJWmm6GgUqSXoqGkplpbPFJSUlKtPFJSUlKvPK8=