<?php
bolt_decrypt( __FILE__ , 'DoTgnt'); return 0;
##!!!##Wlq+sb21w8Cxs7VwkcDArKCxs7uxt7XDrKHFtcLJlcjEwrGslciztcDEub++w4taWsXDtXCVyLO1wMS5v76LWlqzvLHDw3CZvsaxvLm0m7XJcLXIxLW+tMNwlciztcDEub++WstacHBwcH96elpwcHBwcHpworXAv8LEcMS4tXC1yLO1wMS5v75+WnBwcHBwelpwcHBwcHpwkMK1xMXCvnDGv7m0WnBwcHBwen9acHBwcMDFsry5s3C2xb6zxLm/vnDCtcC/wsR4eVpwcHBwy1pwcHBwzVrN