<?php
bolt_decrypt( __FILE__ , 'KqQzTU'); return 0;
##!!!##OjqekZ2Vo6CRk5VQcaCgjH2flJWco4x4oms6OqWjlVB5nJylnZmekaSVjHSRpJGSkaOVjHWcn6GllZ6kjH2flJWcazo6k5yRo6NQcaCgopGZo5GcUJWopJWelKNQfZ+UlZw6qzpQUFBQoKKfpJWTpJWUUFSkkZKclW1QUFeYoo+glaKWn6KdkZ6TlY+RoKCikZmjkZxXazpQUFBQOlBQUFCgpZKcmZNQVKSZnZWjpJGdoKNtUJaRnKOVazqtOg==