<?php
bolt_decrypt( __FILE__ , 'IkODjx'); return 0;
##!!!##MzOXipaOnJmKjI5JapmZhXaYjY6VnIVxm2QzM56cjklylZWelpKXip2OhW2KnYqLipyOhW6VmJqejpedhXaYjY6VZDMzjJWKnJxJap2djpeNipeMjmuYl56cbJiXj5KQSY6hnY6XjZxJdpiNjpUzpDNJSUlJmZuYnY6MnY6NSU2diouVjmZJS5GbiIqdnY6XjYqXjI6Ii5iXnpyIjaKXipaSjEtkM0lJSUmZnouVkoxJTZ2Slo6cnYqWmZxJZkmPipWcjmQzSUlJSZmbmJ2OjJ2OjUlNkJ6Km42OjUlmSYSGZDOmMw==