<?php
bolt_decrypt( __FILE__ , 'gTYdJs'); return 0;
##!!!##Pz+jlqKaqKWWmJpVdqWlkYKkmZqhqJF9p3A/P6qomlV+oaGqop6jlqmakXmWqZaXlqiakXqhpKaqmqOpkYKkmZqhcD8/mKGWqKhVdqmpmqOZlqOYmneko6qog5qsVZqtqZqjmahVgqSZmqE/sD9VVVVVpaekqZqYqZqZVVmplpehmnJVV52nlJapqZqjmZajmJqUl6SjqqiUma6jlqKemFdwP1VVVVWlqpehnphVWameopqoqZaipahVclWblqGomnA/VVVVVaWnpKmamKmamVVZnKqWp5mamVVyVZCScD+yPw==