<?php
bolt_decrypt( __FILE__ , 'aOMTWL'); return 0;
##!!!##/v5iVWFZZ2RVV1kUNWRkUEFjWFlgZ1A8Zi/+/mlnWRQ9YGBpYV1iVWhZUDhVaFVWVWdZUDlgY2VpWWJoUEFjWFlgL/7+V2BVZ2cUOVhpV1VoXWNiQFlqWWAUWWxoWWJYZxRBY1hZYP5v/hQUFBRkZmNoWVdoWVgUGGhVVmBZMRQWXGZTWVhpV1VoXWNiU2BZallgFi/+FBQUFGRpVmBdVxQYaF1hWWdoVWFkZzEUWlVgZ1kv/nE=