<?php
bolt_decrypt( __FILE__ , 'dAIRdQ'); return 0;
##!!!##//9jVmJaaGVWWFoVNmVlUUJkWVphaFE9ZzD//2poWhU+YWFqYl5jVmlaUTlWaVZXVmhaUTphZGZqWmNpUUJkWVphMP//WGFWaGgVOmJlYWRuWlo3WmNcVmFeFVptaVpjWWgVQmRZWmH/cP8VFRUVZWdkaVpYaVpZFRlpVldhWhUyFRddZ1RaYmVhZG5aWlRXWmNcVmFeFzD//xUVFRVlZ2RpWlhpWlkVGVxqVmdZWlkVMhVQF11nVFdjVF5ZF1Iw//8VFRUVZWpXYV5YFRlpXmJaaGlWYmVoFTIVW1ZhaFow/3L/