<?php
bolt_decrypt( __FILE__ , 'kODwqA'); return 0;
##!!!##MTGViJSMmpeIioxHaJeXg3SWi4yTmoNvmWIxMZyajEdwk5OclJCViJuMg2uIm4iJiJqMg2yTlpicjJWbg3SWi4yTYjExipOImppHbJ2MlZtHjJ+bjJWLmkd0louMkzGiMUdHR0eXmZabjIqbjItHS5uIiZOMZEdJj5mGjJ2MlZuaSWIxR0dHR5eZlpuMipuMi0dLjZCTk4iJk4xkgk6MnYyVm4abkJuTjE5TR06MnYyVm4aam4iZm05TR06MnYyVm4aMlYtOhGIxpDE=