<?php
bolt_decrypt( __FILE__ , 'khqOOW'); return 0;
##!!!##Q0OnmqaerKmanJ5ZeqmplYaonZ6lrJWBq3RDQ66snlmCpaWupqKnmq2elX2arZqbmqyelX6lqKqunqetlYaonZ6ldENDnKWarKxZf6Kxnp2MmqWaq7JZnrGtnqedrFmGqJ2epUO0Q0NZWVlZqauorZ6crZ6dWV2tmpulnll2WVuhq5iforGenZiepqmYrJqlmquyW3RDQ1lZWVmprpulopxZXa2ipp6srZqmqaxZdlmfmqWsnnRDQ1lZWUNZWVlZQ7ZD