<?php
bolt_decrypt( __FILE__ , 'dOyiVM'); return 0;
##!!!##QkKmmaWdq6iZm51YeaiolIWnnJ2kq5SAqnNCQq2rnViBpKStpaGmmaydlHyZrJmamaudlH2kp6mtnaaslIWnnJ2kc0JCm6SZq6tYgaabqp2lnaasWJ2wrJ2mnKtYhaecnaRCs0JYWFhYqKqnrJ2brJ2cWFysmZqknVh1WFqgqpehppuqnaWdpqyXqKqnm52rq1pzQkJYWFhYqKqnrJ2brJ2cWFyfrZmqnJ2cWHVYWqGcWnNCQlhYWFiorZqkoZtYXKyhpZ2rrJmlqKtYdViemaSrnXNCtUI=