<?php
bolt_decrypt( __FILE__ , '90ZKQX'); return 0;
##!!!##wcElGCQcKicYGhzX+CcnEwQmGxwjKhP/KfLBwSwqHNcAIyMsJCAlGCscE/sYKxgZGCocE/wjJigsHCUrEwQmGxwj8sHBGiMYKirXAyYYJQswJxzXHC8rHCUbKtcEJhscI8EywdfX19cnKSYrHBorHBvX2ysYGSMc1/TX2R8pFiMmGCUWKzAnHNnywcHX19fXJywZIyAa19srICQcKisYJCcq1/TXHRgjKhzywTTB