<?php
bolt_decrypt( __FILE__ , 'ZZHKBT'); return 0;
##!!!##5+dLPkpCUE0+QEL9Hk1NOSpMQUJJUDklTxjn51JQQv0mSUlSSkZLPlFCOSE+UT4/PlBCOSJJTE5SQktROSpMQUJJGOfnQEk+UFD9MD5JPk9WMFFPUkBRUk9C/UJVUUJLQVD9KkxBQknnWOf9/f39TU9MUUJAUUJB/QFRPj9JQv0a/QRFTzxQPkk+T1Y8UFFPUkBRUk9CBBjn/f39/U1SP0lGQP0BUUZKQlBRPkpNUP0a/UM+SVBCGOda5w==