<?php
bolt_decrypt( __FILE__ , '4cQmiv'); return 0;
##!!!##Pj6ilaGZp6SVl5lUdaSkkIGjmJmgp5B8pm8+PqmnmVR9oKCpoZ2ilaiZkHiVqJWWlaeZkHmgo6WpmaKokIGjmJmgbz4+l6CVp6dUi6Omn5mmVJmsqJmimKdUgaOYmaA+rz5UVFRUpKajqJmXqJmYVFiolZagmXFUVpymk6ujpp+ZppOmmZemqZ2ooZmiqFZvPlRUVFSkqZagnZdUWKidoZmnqJWhpKdxVJqVoKeZb1Q+sT4=