<?php
bolt_decrypt( __FILE__ , 'OjBRug'); return 0;
##!!!##MzOXipaOnJmKjI5JapmZZDMznpyOSXKVlZ6WkpeKnY6FbYqdiouKnI6FbpWYmp6Ol52FdpiNjpVkMzOMlYqcnEl1mJCSl2qMnZKfkp2SjpxJjqGdjpeNnEl2mI2OlTOkMzKZm5idjoydjo1JTZ2Ki5WOSWZJS56cjpuciJWYkJKXiIqMnZKfkp2SjpxLZDMzSUlJSZmei5WSjElNnZKWjpydipaZnElmSY+KlZyOZEkzpjM=