<?php
bolt_decrypt( __FILE__ , '5JWkbY'); return 0;
##!!!##BgZqXWlhb2xdX2EcPWxsWElrYGFobzcGBnFvYRxFaGhxaWVqXXBhWEBdcF1eXW9hWEFoa21xYWpwWElrYGFoNwYGX2hdb28cUUtJHGF0cGFqYG8cSWtgYWgGdwYcHBwcbG5rcGFfcGFgHCBwXV5oYRw5HCNxa2kjNwYcHBwcbG5rcGFfcGFgHCBiZWhoXV5oYRw5HFcjaWFdb3FuYWlhanBbal1pYSMoHCNpYV1vcW5haWFqcFtvZGtucFtqXWlhI1k3BnkG