<?php
bolt_decrypt( __FILE__ , 'ekXRZU'); return 0;
##!!!##MzOXipaOnJmKjI5JapmZhXaYjY6VnGQzM56cjklylZWelpKXip2OhW2KnYqLipyOhW6VmJqejpedhXaYjY6VZDOenI5JbWtkMzOMlYqcnEl+nI6bdZiQSY6hnY6XjZxJdpiNjpUzpDMzMpmbmJ2OjJ2OjUlNnYqLlY5JZklQnpyOm4iVmJCcUGQzSUlJSZmbmJ2OjJ2OjUlNkJ6Km42OjUlmSYRQko1QhmQzM0lJSUmZm5idjoydjo1JTY2KnY6cSWZJhDNJSUlJSUlJSVCMm46KnY6NiIqdUFVQnpmNip2OjYiKnVAzSUlJSYZkMzOmMw==