<?php
bolt_decrypt( __FILE__ , 'AStf0V'); return 0;
##!!!##/v5iVWFZZ2RVV1kUNWRkUEFjWFlgZy/+/mlnWRQ9YGBpYV1iVWhZUDhVaFVWVWdZUDlgY2VpWWJoUEFjWFlgL/5pZ1kUODYv/v5XYFVnZxRJZ1lmQGNbFFlsaFliWGcUQWNYWWD+b/7+/WRmY2hZV2hZWBQYaFVWYFkUMRQbaWdZZlNgY1tnGy/+FBQUFGRmY2hZV2hZWBQYW2lVZlhZWBQxFE8bXVgbUS/+/hQUFBRkZmNoWVdoWVgUGFhVaFlnFDEUT/4UFBQUFBQUFBtXZllVaFlYU1VoGyAbaWRYVWhZWFNVaBv+FBQUFFEv/v5x/g==